version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db-perf-postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: performance_lab
    ports:
      - "5432:5432"


  

